#!/usr/bin/env python
import os
from sys import argv, exit
from textwrap import wrap

from engine.answers import ask

if __name__ == "__main__":
    if len(argv) < 3:
        print("Usage: answer <query> <topic> [model]")
        exit(1)

    verbose = os.getenv("BOSSBOT_VERBOSE")
    query = argv[1]
    topic = argv[2]
    model = argv[3] if len(argv) == 4 else os.getenv("BOSSBOT_MODEL", "default")

    think, answer, seq, seconds = ask(query, topic, model)
    print(f"Topic: {topic} [{seq}]")
    if verbose:
        print("Think:")
        for t in think:
            for line in wrap(t):
                print(f"  {line}")
            print()
    print("Answer:")
    for a in answer:
        for line in wrap(a):
            print(f"  {line}")
        print()
    model = os.getenv("BOSSBOT_MODEL", "no model")
    print(f"Answer computed in {seconds:,} seconds with {model}")
