#!/usr/bin/env python
"""
Reset ChromaDB and add documents to the database.
"""

from glob import glob
from hashlib import sha1
from pathlib import Path

import chromadb

BATCH_SIZE = 1000


def add_document(
    collection: chromadb.Collection, file_path: str, context_sentences: int = 3
):
    """
    TODO: A better splitter/chunker is almost surely using LangChain
    https://gist.github.com/tazarov/e66c1d3ae298c424dc4ffc8a9a916a4a
    """
    document = Path(file_path).read_text()
    sentences = document.replace("\n", " ").split(".")

    chunks = set()
    for i in range(len(sentences) - context_sentences):
        chunks.add(".".join(sentences[i : i + context_sentences]))
    all_chunks = list(chunks)
    all_ids = [sha1(chunk.encode()).hexdigest() for chunk in chunks]

    for n in range(len(chunks) // BATCH_SIZE):
        chunks = all_chunks[n * BATCH_SIZE : (n + 1) * BATCH_SIZE]
        ids = all_ids[n * BATCH_SIZE : (n + 1) * BATCH_SIZE]
        collection.add(documents=chunks, ids=ids)
        print(".", end="", flush=True)

    print()
    return collection


if __name__ == "__main__":
    client = chromadb.PersistentClient()
    client.reset()  # Clear the database before adding new documents
    collection = client.create_collection(name="BossBot")

    for document in glob("assets/text/*.txt"):
        print(f"Adding {document} to the database.")
        collection = add_document(collection, document)

    print(f"Records: {collection.count():,}")
