#!/usr/bin/env python
import os
from pathlib import Path
from time import sleep
import sys
import yaml

from engine.watch import poll_queries

if __name__ == "__main__":
    config = Path.home() / ".bossbot.yaml"
    if config.exists():
        for k, v in yaml.safe_load(config.read_text()).items():
            os.environ[k] = v

    missing = False
    for key in [
        "BOSSBOT_ENGINE_NAME",
        "BOSSBOT_ENGINE_TOKEN",
        "BOSSBOT_MODEL",
        "TOKENIZERS_PARALLELISM",
    ]:
        if not os.getenv(key):
            print(f"Missing environment variable: {key}")
            missing = True
    if missing:
        sys.exit(1)

    engine = os.getenv("BOSSBOT_ENGINE_NAME", "")
    token = os.getenv("BOSSBOT_ENGINE_TOKEN", "")
    while True:
        poll_queries(engine=engine, token=token)
        sleep(1)
